### ISSUE TITLE
Backend: API: Create Ingredient Endpoints

### ISSUE THREAD

**Issue by LenVej** [SE-TINF22B6/CookHub#102]
### Create Ingredient Endpoints
# To-do list, if necessary:
1. [x] Get by Name
2. [x] Get by ID
3. [x] Get a List with all ingredients
4. [x] Create new Ingredient
5. [x] Delete Ingredient
