### ISSUE TITLE
Frontend: Find Recipes: Implement Search Bar and Find Button

### ISSUE THREAD

**Issue by Stev3eM** [SE-TINF22B6/CookHub#109]
## Enhancement
# To-do list, if necessary:
1. [ ] Implement Search Bar
2. [ ] Implement Find Button
3. [ ] Create Issue for backend team: Implementation of functionality
